#!/usr/bin/env bash

# Apito-Aspnet is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Apito-Aspnet is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Apito-Aspnet. If not, see <https://www.gnu.org/licenses/>.

# DEBUG SETTINGS
set -euo pipefail

# ====== DEPENDENCIES
# DEPS=(bash cat curl fzf awk grep) # TODO: check if dependencies are present

# ====== GENERAL INFORMATION
# https://www.gnu.org/software/bash/manual/bash.html#Brace-Expansion

# SECURITY INFO
# USERNAME=$(awk --field-separator '=' '/USER_NAME/ {print $2}' ./envs/security)
# PASSWORD=$(awk --field-separator '=' '/USER_PASSWORD/ {print $2}' ./envs/security)

# PATH DEFAULTS
PORT="5000"
FINAL_PATH="localhost:$PORT"
FILENAME=./apitest-commands
# COLLECTION OR SINGLE ENTITY
if [ $# -eq 1 ]; then
# filter ID entries
SELECTED="$(awk '/ID/ {print $0; print}' $FILENAME | fzf)"
else
# ignore ID entries
SELECTED="$(grep -v ID $FILENAME | fzf)"
fi

ENTRIES="${SELECTED##*: }"
HTTP_METHOD="${ENTRIES%% *}"
REST="${ENTRIES#* }"

# FINAL COMMAND
COMMAND="$FINAL_PATH$REST"
[ $# -eq 1 ] && COMMAND="${COMMAND/ID/$1}"

# ====== RUN

curl \
    --header "accept: application/json" \
    --request "$HTTP_METHOD" \
    --url "$COMMAND"

    # --user "$USERNAME:$PASSWORD" \

# TODO: Add CLI options
# INFORMATION="apitest - GPLv3
# METHOD: $HTTP_METHOD
# REST: $REST
# PORT: $PORT
# PATH: $COMMAND
# "
# echo -e $INFORMATION
